---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-files
  namespace: kube-system
  labels:
    app: traefik
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "mystorage" # use this if used with a custom storage class
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:2.2
        name: traefik
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        volumeMounts:
          - name: traefik-files
            mountPath: /var/lib/traefik
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api.insecure
        #- --api.dashboard # uncomment to enable dashboard
        - --providers.kubernetescrd
        - --accesslog
        - --entrypoints.web.Address=:80
        #- --entrypoints.web.http.redirections.entryPoint.to=websecure  # enable to redirect all http to https traffic, no middleware needed
        - --entrypoints.websecure.Address=:443
        - --certificatesResolvers.myresolver.acme.email=admin@email.com # change me to a valid e-mail address
        - --certificatesresolvers.myresolver.acme.storage=/var/lib/traefik/acme.json
        - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory # change to https://acme-v02.api.letsencrypt.org/directory for valid certificates
        - --certificatesResolvers.myresolver.acme.tlsChallenge=true
      volumes:
        - name: traefik-files
          persistentVolumeClaim:
            claimName: traefik-files
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
